### ISSUE TITLE
Ability to save markers on map and make it an actual mobile app 

### ISSUE THREAD

**Issue by BilElSicario** [PLTytus/GTAWeb#58] opened 2024-04-25 23:21 UTC
Save markers on map just like GTA Lens and make it an actual mobile app, not just save it in screen, because the status goes offline alone when not in the “app” for a while

**Comment by PLTytus** [comment] 2024-04-26 09:51
> Save markers on map just like GTA Lens

You mean logging and saving for an account? If so, then it is duplicate of https://github.com/PLTytus/GTAWeb/issues/18, which is already work in progress and it will take some time - cannot say how much at the momemnt.

> make it an actual mobile app

I would have to work from scratch, probably on two new projects - for Android and iOS, with website it makes three separate projects - and the website project is already enormous huge, honestly I didn't expect it will grow so much. So, the proper mobile app is out of option at the moment.

> Save markers on map just like GTA Lens and make it an actual mobile app, not just save it in screen, because the status goes offline alone when not in the “app” for a while

You referring to toolkit, right? Do you use the "save it in screen" option? This option is avaiable separately on subpages, from which subpage you added it to home screen? Try adding it from toolkit. That one should not reload in background (the status goes to offline after reload) so fast. On mine it was working almost 24 hours ans still was Online, but the progress of businesses was wrong. I made some changes in updating toolkit data, currently testing if it will return proper results after idling for a longer time - for new code work for you, better close and re-open 'app'.
If it is refereshing to fast for you, maybe try to switch to the app and lock screen while it is diplayed without going to home screen or another app.

**Comment by BilElSicario** [comment] 2024-04-26 13:38
> You mean logging and saving for an account?
yeah it's what I meant 
> You referring to toolkit, right? Do you use the "save it in screen" option? This option is avaiable separately on subpages, from which subpage you added it to home screen?
- Yes 
- Yes
- Added it from toolkit but on chrome and I'm on IOS, maybe safari is better for this refreshing issue 
> If it is refereshing to fast for you, maybe try to switch to the app and lock screen while it is diplayed without going to home screen or another app.
that will probably fix it for me, I'll try that

**Closed** 2024-04-29 07:20 UTC
Labels: issue, duplicate, suggestion, done/fixed
