### ISSUE TITLE
Multi-Character support

### ISSUE THREAD

**Issue by cochvik** [PLTytus/GTAWeb#24] opened 2023-10-16 13:27 UTC
**Describe your idea:**
It would be really helpful to be able to track collectibles (e.g. ghosts, UFOs) for multiple character slots - generally two slots available per account, but some folks may want to track progress for more than one account on a system, so an arbitrary number of accounts would be preferred - perhaps with named slots. This could be part of import/export support from https://github.com/PLTytus/GTAWeb/issues/18...

Right now this can be accomplished to some extent with different browsers (on the same system, different systems, different profiles within browsers, etc.), but it would be really handy to be able to do it within the same browser. 👍

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
(note two misspellings in the form in the line above ^ - 'somthing' and 'webiste' vs 'something' and 'website')

**Comment by PLTytus** [comment] 2023-10-16 17:34
Duplicate of https://github.com/PLTytus/GTAWeb/issues/18

**Closed by PLTytus** 2023-10-16 17:34 UTC
Labels: suggestion

**Comment by cochvik** [comment] 2023-10-17 02:37
I don't agree that this is a strict duplicate of #18 - either suggestion could be implemented fully independently of the other (sign-in support w/ only a single character or multi-character support just from local storage/cookies). I mention it in relation to #18 because it could be something to consider if/when implementing #18, and may have some significant overlap in terms of underlying architecture support. But solving #18 won't inherently address this suggestion...

**Comment by cochvik** [comment] 2023-10-17 02:45
Perhaps the example is insufficient to explain the use case - I routinely use both characters in my GTA account, one I consider 'Primary' and one 'Secondary'. This site is *super* useful for locating stuff on the daily, but with two characters, gets a bit unwieldy to track collectibles over more than one session.

I would like to track UFOs spotted on my Primary character, and then press a button or two on the page to switch to my Secondary character and track their UFO progression - same PC, same browser, just different set of UFOs 'marked'. Currently, I can only track progress for one of them, unless I use a separate browser or another profile within the browser (which is effectively a separate 'browser' in some respects).

There's at least one fren I know who is apparently a masochist and did the 300-pumpkin search on each of his _**six**_ characters (three accounts, two slots per account) - I have to imagine the ability to track collectibles on an arbitrary number of accounts would be useful to him... (y)
