### ISSUE TITLE
Vehicle locations

### ISSUE THREAD

**Issue by Jo-Saiyan** [PLTytus/GTAWeb#42] opened 2024-01-18 10:26 UTC
You should add the vehicles and the spawn locations where they spawn.

**Comment by PLTytus** [comment] 2024-01-18 10:28
Duplicate of https://github.com/PLTytus/GTAWeb/issues/10

**Closed by PLTytus** 2024-01-18 10:28 UTC
Labels: duplicate, suggestion

**Comment by Jo-Saiyan** [comment] 2024-01-18 10:33
On the cayo perico islandOn Jan 18, 2024, at 05:28, PLTytus ***@***.***> wrote:﻿
Closed #42 as completed.

**Comment by PLTytus** [comment] 2024-01-18 10:35
Then, it is duplicate of https://github.com/PLTytus/GTAWeb/issues/31
