### ISSUE TITLE
GTAWEB.Eu Mobile App on iOS

### ISSUE THREAD

**Issue by Gta211** [PLTytus/GTAWeb#75] opened 2024-11-03 06:42 UTC
**Describe your idea:**
...
Can we please get a GTAWEB.Eu Mobile App on iOS for faster & more convenient access. Please!!
**Examples (if you was inspired by some other website or project):**
...

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
...

**Comment by PLTytus** [comment] 2024-11-03 09:22
Duplicate of https://github.com/PLTytus/GTAWeb/issues/58

https://github.com/PLTytus/GTAWeb/issues/58#issuecomment-2079037279
> I would have to work from scratch, probably on two new projects - for Android and iOS, with website it makes three separate projects - and the website project is already enormous huge, honestly I didn't expect it will grow so much. So, the proper mobile app is out of option at the moment.

**Closed by PLTytus** 2024-11-03 09:22 UTC
Labels: suggestion
