### ISSUE TITLE
Account system

### ISSUE THREAD

**Issue by tokyoboy-vs** [PLTytus/GTAWeb#60] opened 2024-05-24 18:22 UTC
**Describe your idea:**
Implement an account system to save and track user progress on icons, including those found, hidden, and marked as done.

**Examples (if you were inspired by another website or project):**
This idea is inspired by interactive map websites for various games, where tracking progress is essential.

**Additional context (if you have something more to add, e.g., how it will help or improve the website):**
This feature will greatly enhance the website by allowing users to track their progress across devices. For example, if I start tracking LD Organics Products on my phone and stop halfway, I can continue from my PC without losing progress. This is crucial for maintaining consistency and motivation in completing tasks.

**Comment by PLTytus** [comment] 2024-05-24 21:41
Work in progress (will take some time). Duplicate of https://github.com/PLTytus/GTAWeb/issues/18.

**Closed** 2024-05-24 21:41 UTC
Labels: duplicate, suggestion
